### ISSUE TITLE
[C-DET-11] 답글의 댓글 삭제하기

### ISSUE THREAD

**Issue by weejihye** [PeerFlow-TeamA/peerflow-BE#17]
**관련 이슈 🤝**

#15 #16

<br><br>
**API 코드 🔢**

C-DET-11

<br><br>
**API detail page 📚**

[답글의 댓글 삭제하기](https://peer-study.notion.site/peerflow-api-5898f07da57546669a021e033fea47e9?p=3dec72dfb8a74306bc28d17835c6642f&pm=s)

<br><br>
**작업 URL 🔗**

/v1/answer/comment/{commentId}

**Comment by Two-Jay** [comment]
feat/answerComment 에서 함께 작업합니다.
