### ISSUE TITLE
[B-WRI-04] 게시글(질문) 삭제하기

### ISSUE THREAD

**Issue by weejihye** [PeerFlow-TeamA/peerflow-BE#6]
**관련 이슈 🤝**

#4 #5

<br><br>
**API 코드 🔢**

B-WRI-04

<br><br>
**API detail page 📚**

[게시글(질문) 삭제하기](https://peer-study.notion.site/peerflow-api-5898f07da57546669a021e033fea47e9?p=4d15cf0d44704f1e95f8567d6e1bd9ce&pm=s)

<br><br>
**작업 URL 🔗**

/v1/question/{questionId}

**Comment by Two-Jay** [comment]
이슈관련 브랜치 PR 후 머지 완료

차후 생기는 고도화 및 버그 수정은 별도의 이슈를 생성하여 다룹니다.

고생 많으셨어요 :)
