### ISSUE TITLE
[C-DET-02] 답글 수정하기

### ISSUE THREAD

**Issue by weejihye** [PeerFlow-TeamA/peerflow-BE#9]
**관련 이슈 🤝**

#8 #10

<br><br>
**API 코드 🔢**

C-DET-02

<br><br>
**API detail page 📚**

[답글 수정하기](https://peer-study.notion.site/peerflow-api-5898f07da57546669a021e033fea47e9?p=5de7277f90c843939e4a22bd9ea9fcc2&pm=s)

<br><br>
**작업 URL 🔗**

/v1/answer/{answerId}

**Comment by Two-Jay** [comment]
feat/answer 브렌치에서 작성합니다.
